### ISSUE TITLE
Connection Closed after reboot of miniserver...

### ISSUE THREAD

**Issue by SteeveK** [codmpm/node-red-contrib-loxone#10]
Hello (i'm french...),

Great job !!!!!
I've a problem with CONTROL IN : when i rebooted my miniser, the CONTROLS IN are no reconnected, they are in yellow with CONNECTION CLOSED.
I've to update the miniserver in node-red to get again CONNECTED...
Could you please help me and excuse me for my horrible english :-)

Thanks.

**Comment by alladdin** [comment]
This is issue in new backend class node-lox-ws-api.
I was fixed it in new version (0.4.2) of that library.

**Comment by SteeveK** [comment]
Ok and thanks, i will waiting new version 0.4.2...

**Comment by codmpm** [comment]
I will include the new node-lox-ws-api 0.4.2 into node-red-contrib-loxone in the next days. Did not had any time and have to build a better testing environment.

**Comment by SteeveK** [comment]
Ok thanks a lot

**Comment by codmpm** [comment]
Updated in node-red-contrib-loxone 0.6.0

**Comment by mapchen** [comment]
hello,

can it be possible that this error came back? After power outages I assume my raspberry comes back faster then the miniserver. That means Loxone Nodes do not have the miniserver structure and are now working. After a restart of the flows everything works fine again

**Comment by codmpm** [comment]
I will have a look into this when I finally manage to work on the other issues.

**Comment by gbrehmer** [comment]
I have similar problems. During FW-Updates of miniserver the miniserver is several minutes not available. node-red tries to reconnect but it seems that reconnect attempts have some limits set?! Is it possible to add some configuration to increase such limits or try counts?

**Comment by codmpm** [comment]
Please check with 0.10.6, should be fixed.
