### ISSUE TITLE
extending node control-in or new node

### ISSUE THREAD

**Issue by kkloesener** [codmpm/node-red-contrib-loxone#15]
Is there a possibility to extend the msg object from control-in node to have all propertys like category, room, control and state within the object?

I would also be interested if i can have a wildcards to select some property, e.g. select temperature and get all Events for any room.
For ease of programming with node-red this could/should be a new node "event stream in"

**Comment by codmpm** [comment]
For the first point: Prove me wrong, but I think the control-in node already give's all the wanted data. See the first example here: https://github.com/codmpm/node-red-contrib-loxone

```
{
    payload: 20.8125,
    topic: "test ds18b20",
    state: "value",
    room: "Serverraum",
    category: "Temperatur",
    details: {
        format: "%.1f°"
    },
    type: "InfoOnlyAnalog"
}
```

Nevertheless I've just tried it with a switch and only get `1` in `msg.payload` and nothing else.
I will have to investigate...

For the second question: Currently only events of the selected items from control-in are parsed. It could be possible to receive all events based on a selected room or category. 
But is this realy needed? Could you give an example?

**Comment by kkloesener** [comment]
actually i only get the value of the control in msg.payload from control-in node

i'm trying to offload the complete statistics from loxone to influxdb/grafana
now i would need for every data input one node, but with one node per category it would be much simpler.

**Comment by codmpm** [comment]
As said, I will have a look at the first problem.

I will check on how to do a category node or something like this. Any other input on this topic?

**Comment by codmpm** [comment]
You were right. I've introduced a bug in `0.6.1` that prevented parsing the ever since present info for the control-in node. Fixed in `0.6.2` - see the msg-object as stated in the first example.

```
{ 
    payload: 1,
    topic: 'Schalter',
    state: 'active',
    room: 'Wohnzimmer',
    category: 'Beleuchtung',
    details: null,
    type: 'Switch' 
}
```

**Comment by kkloesener** [comment]
I'm sorry to tell you that even with the new version i do not get the full msg-object and only msg.payload

**Comment by codmpm** [comment]
Hm. Did you restart nodered after updating node-red-contrib-loxone and reload your browser?
If you see the "activate connection" checkbox in the miniserver config, you have still `0.6.1`.

Did an update on a Pi I have laying around for testing purposes which was at `0.6.0`. I've updated to `0.6.2`, restarted nodered and hooked a debug node with "complete msg-object" to a control-in node. Worked as described.

```
└─┬ node-red-contrib-loxone@0.6.2 
  └─┬ node-lox-ws-api@0.4.3 
    └── websocket@1.0.25 
```

What's the output of `npm list node-red-contrib-loxone` when you execute it in `~/.node-red`?

**Comment by codmpm** [comment]
I've added the suggested stream-in-node in `0.7.0`.

Please see the info and the notes as you will get _every_ state from _every_ control in the room/category on connect/reconnect/full-deploy. On occurance only the state that fired the event generates a message.

**Comment by codmpm** [comment]
See here for explanation and examples of the stream-in node: https://www.loxforum.com/forum/faqs-tutorials-howto-s/86293-entwicklung-node-red-contrib-loxone-für-node-red?p=125759#post125759 (german)
