### ISSUE TITLE
keepalive in log

### ISSUE THREAD

**Issue by HarterHorst** [codmpm/node-red-contrib-loxone#16]
Hi,

I have a console with tail/pm2 log open to see what's going on with node-red. The loxone node spams the log every two minutes. Is there a chance to drill down the verbose level so the log stays clean.

thanx
horst

**Comment by codmpm** [comment]
Hi @HarterHorst,

the keepalive time is set to 2 minutes inside node-lox-ws-api and is currently not parametrable. Additionaly, the connection the miniserver has to be kept alive at least every 5 minutes. 

See page 21 of the websocket documenation from Loxone: https://www.loxone.com/dede/wp-content/uploads/sites/2/2016/08/0900_Communicating-with-the-Miniserver.pdf?x94623

It is possible to simply disable the log output for the keepalive request. Not thought about this, yet.

**Comment by codmpm** [comment]
Removed keepalive log message in `0.7.0`
