### ISSUE TITLE
connection to Loxone lost when uploading new configuration to loxone

### ISSUE THREAD

**Issue by adampelikan** [codmpm/node-red-contrib-loxone#17]
Hello guys,

first  thing - thank you so much for this great project...usability of Loxone gets much higher...

I'm having issues when uploading new configuration from Loxone Config to Loxone miniserver - connection of Loxone nodes in node-red gets lost. I just need to redeploy or restart node-red to get connection again...

I found similar issues described in other tickets that are already closed with solution in node-red-contrib-loxone 0.6.2 (with node-lox-ws-api 0.4.3). I'm running this version but described issue still appears. Btw. new checkbox "Activate connection?" is checked (but I don't know how does it exactly behave).

Could you please help? Is there something wrong on my side I might overlook?

Regards,
Adam

**Comment by codmpm** [comment]
Hey @adampelikan,

thank you :-)

Please update to the current version as the "activate connection"-checkbox was only present till `0.6.0` and the fixed version for the reconnection bug is `0.6.1`.
Remember to restart your node-red instance and do a full reload of node-red in the browser, then double check your installed version in "Manage Palette" or via the console:

```
cd ~/.node-red
npm list node-red-contrib-loxone 
```

The "activate connection"-checkbox was an idea to deactivate the miniserver-config temporarely, but this was only possible on full-deploy. So, it got removed in `0.6.1` till I have a better solution.

Cheers,
Patrik

**Comment by adampelikan** [comment]
Hi Patrik,

there was fault between keyboard and computer :-)

It seem there I had some mess here - I had two installations of node-red-contrib-loxone: first in ~/.node-red (0.6.0) and second in ~ (0.6.2). So I updated one in ~/.node-red to last version and now everything is OK now.

Thanks a lot

Cheers
