### ISSUE TITLE
Node-Red crashes when Room/Category is set to "Do Not Use"

### ISSUE THREAD

**Issue by schimmi6** [codmpm/node-red-contrib-loxone#21]
Node-Red crashes when Room and/or Category in LoxoneConfig is set to "Do Not Use"

**Comment by codmpm** [comment]
Sorry to get back to you so late.

Is the crash still present in the current version of node-red-contrib-loxone?

**Comment by codmpm** [comment]
closed due "no answer" from opener

**Comment by codmpm** [comment]
Fixed in 0.10.0, see https://www.loxforum.com/forum/faqs-tutorials-howto-s/86293-entwicklung-node-red-contrib-loxone-für-node-red?p=152674#post152674
