### ISSUE TITLE
Nodes get disconnected and others are still connected

### ISSUE THREAD

**Issue by mabunixda** [codmpm/node-red-contrib-loxone#23]
Hi,

i just began integrating our blinds into node-red with alexa and i am observing this pattern:
![nodered-loxone-notconnected](https://user-images.githubusercontent.com/1193145/36190933-b84e1cda-1152-11e8-8ebf-1f50610327a8.png)

Some blinds work correct via alexa. The function block just sets Up/Down as payload when On/Off is sent. 
On the other side blinds that do not work, the gets no status update after a command is sent via alexa.  At this time also other nodes get no status shown in node-red. 
In the console output is no error reported :( 

Is this issue related to #12 ? 

Martin

**Comment by codmpm** [comment]
Hey @mabunixda,

as I have no Alexa I can not test this. Maybe @thmeger can double check if this behavior lies in Alexa or in node-red-contrib-loxone.

The connected/disconnected info is only updated on a full-deploy. That's where #12 ist related as this bit of information in the editor needs to be better.
Nevertheless all nodes are "connected" as long as the single connection to the miniserver is online.

Cheers,
Patrik

**Comment by thmeger** [comment]
I don't have any problems controlling blinds with Node-RED and Alexa via Loxone. 
Please try to create a little Dashboard-button or use a normal inject node to start the specific nodes in that flow and see whether that works in lieu of using Alexa node.

**Comment by mabunixda** [comment]
It is a Loxone problem - the central blinds elements ( "type":"CentralJalousie" ) cannot be controlled via the api. When i change the webservice node to the dedicated blinds then it works as expected.

I do not understand those design principles of loxone software ... 
I gonna update to the latest beta right now and test if there is work still the same. If yes, i gonna open a bug.

**Comment by codmpm** [comment]
I'm with you. 
I have not tested node-red-contrib-loxone to the latest beta, yet.

Just for my head: Can you control `CentralJalousie` from the smartphone-app?

**Comment by mabunixda** [comment]
Yeah you are right ... got it: /FullDown and /FullUp are the correct commands
