### ISSUE TITLE
Miniserver connection error: undefined

### ISSUE THREAD

**Issue by mabunixda** [codmpm/node-red-contrib-loxone#24]
Hi,

in the last days i see very often a 
> Miniserver connection error: undefined
in the debug logs and node-red logs.

how can i debug this problem better? Or is this just in my installation?
Also got this right now ( i saw it now the first time )
> Miniserver connect failed

But afterwards everything is connected again...

**Comment by thmeger** [comment]
Try to use a „Full deploy“ all nodes and have a look whether that fixes the problem.

**Comment by mabunixda** [comment]
I always use a full deploy - seems the default?

**Comment by codmpm** [comment]
Hmm, `undefined` is not satisfying. Can you double check the network connection to the miniserver? Maybe run a `ping <ip-of-miniserver>` on a second terminal while the problem appears.

**Comment by mabunixda** [comment]
i configured telegraf with ping of the miniserver ip and http_reponse of "http://<ip-of-miniserver>/styles/misc.css". Both checks run every 10s .. They do not report any errors.

So i startet a terminal and run ping <ip> - also no packet loss. ping time is about 0.3ms 
In the end i run now node-red-contrib-isonline to check the miniserver ip every second and storing this data into an influxdb. 

I followed the logs of a node-red installation and found these logs
> 19 Mar 21:38:08 - [info] [loxone-miniserver:fadf46a1.f36eb8] Miniserver connected (<ip>:80) using Token-Enc
> 19 Mar 21:38:08 - [info] [loxone-miniserver:fadf46a1.f36eb8] got structure file 2018-03-18 14:09:17
> 19 Mar 21:38:10 - [info] [loxone-miniserver:fadf46a1.f36eb8] Miniserver connected (<ip>:80) using Token-Enc
> 19 Mar 21:38:11 - [info] [loxone-miniserver:fadf46a1.f36eb8] got structure file 2018-03-18 14:09:17

Why are there 2 connections online? There is just 1 loxone-miniserver config node. On another node-red installation i can see 3 connects within a second and 3 "got structure file" log messages. 

As far as i understand the code there should only be a single connection to the miniserver

**Comment by codmpm** [comment]
Hey @mabunixda, sorry for getting back so late.

As you say, there's nothing in the node that tries to connect two times to the miniserver. Could you check how often the loxone-online-node emits `true`?

Maybe we can debug this together, ping me on nodered.slack.com (pmayer)

**Comment by mabunixda** [comment]
Hi @codmpm , no problem i upgaded to the latest beta 9.3.3.21 and now those problems are not present anymore

I guess the root cause was within the loxone software and not within the node
