### ISSUE TITLE
buildMsgObject sets room to category's value and leaves category null

### ISSUE THREAD

**Issue by Jofagi** [codmpm/node-red-contrib-loxone#25]
Original problem discussion:
https://www.loxforum.com/forum/german/software-konfiguration-programm-und-visualisierung/126152-beispiel-loxone-mit-node-red-auf-rpi-3-influxdb-und-grafana-visu?p=155026#post155026

**Comment by codmpm** [comment]
Oh damn that copy pasta.... your are absolutely right.
