### ISSUE TITLE
Ghost connection profiles and connection dropping

### ISSUE THREAD

**Issue by xAPPO** [codmpm/node-red-contrib-loxone#28]
I have 3 Loxone miniservers which is a situation I'm sure you hadn't expected to support (although it would be nice). I can get around this by running  three NodeRED instances which I am not doing.. yet.

However when I add a Loxone component and configure the connection it often fails to connect for a long time but then eventually does only to disconnect a few minutes later, sometimes up to an hour or two. (see NodeRED log at end). My network is very dependable. This posts lots of error messages to the log of course. What's very strange is that if I then remove all Loxone nodes from the flows I still see these error messages and NodeRED still shows connection attempts !  Something remains, seems it's retained in NodeRED.

At one stage I created a second connection profile and then I saw that both connections were trying to be established from NodeRED (to two different IP addresses). So I deleted the second connection profile but still they both persist.  The NodeRED Configuration showed 0 nodes using the profile and I deleted it there too but same issue.   The connection does dissappear from the dropdown.

I tried removing the Loxone nodes from the palette and via npm and also deleting the folder in my home directory but if I then add them back then still this happens.   I'm now at the stage where I have to keep rebuilding NodeRED from scratch to remove these error messages and connection attempts.

Any ideas ?

```
1 | node-red | 28 Jul 14:39:15 - [info] [loxone-miniserver: e42aefbc.0dfdc] Miniserver connected (192.168.1.95:80) using token-enc 
1 | node-red | 28 Jul 14:39:15 - [error] [loxone-miniserver: e42aefbc.0dfdc] Miniserver connection error: undefined 
1 | node-red | 28 Jul 14:39:15 - [info] [loxone-miniserver: e42aefbc.0dfdc] connection closed 
1 | node-red | 28 Jul 14:39:15 - [info] [loxone-miniserver: e42aefbc.0dfdc] Miniserver connected (192.168.1.95:80) using token-enc 
1 | node-red | 28 Jul 14:39:15 - [error] [loxone-miniserver: e42aefbc.0dfdc] Miniserver connection error: undefined 
1 | node-red | 28 Jul 14:39:15 - [info] [loxone-miniserver: e42aefbc.0dfdc] connection closed
1 | node-red | 28 Jul 14:39:16 - [info] [loxone-miniserver: e42aefbc.0dfdc] Miniserver connected (192.168.1.95:80) using token-enc 
1 | node-red | 28 Jul 14:39:16 - [info] [loxone-miniserver: e42aefbc.0dfdc] got structure file 2018-07-22 21:10:33
1 | node-red | 28 Jul 14:39:17 - [info] [loxone-miniserver: e42aefbc.0dfdc] Miniserver connected (192.168.1.95:80) using token-enc 
1 | node-red | 28 Jul 14:39:17 - [info] [loxone-miniserver: e42aefbc.0dfdc] Miniserver connected (192.168.1.95:80) using token-enc 
1 | node-red | 28 Jul 14:39:17 - [info] [loxone-miniserver: e42aefbc.0dfdc] got structure file 2018-07-22 21:10:33 
1 | node-red | 28 Jul 14:39:17 - [info] [loxone-miniserver: e42aefbc.0dfdc] got structure file 2018-07-22 21:10:33
1 | node-red | 28 Jul 14:43:28 - [info] [loxone-miniserver: e42aefbc.0dfdc] connection closed 
1 | node-red | 28 Jul 14:43:28 - [info] [loxone-miniserver: e42aefbc.0dfdc] connection closed 
1 | node-red | 28 Jul 14:43:28 - [info] [loxone-miniserver: e42aefbc.0dfdc] connection closed 
1 | node-red | 28 Jul 14:43:30 - [info] [loxone-miniserver: e42aefbc.0dfdc] Miniserver connected (192.168.1.95:80) using token-enc 
1 | node-red | 28 Jul 14:43:30 - [error] [loxone-miniserver: e42aefbc.0dfdc] Miniserver connection error: undefined 
1 | node-red | 28 Jul 14:43:30 - [info] [loxone-miniserver: e42aefbc.0dfdc] connection closed 
1 | node-red | 28 Jul 14:43:30 - [info] [loxone-miniserver: e42aefbc.0dfdc] Miniserver connected (192.168.1.95:80) using token-enc
1 | node-red | 28 Jul 14:43:30 - [error] [loxone-miniserver: e42aefbc.0dfdc] Miniserver connection error: undefined 
1 | node-red | 28 Jul 14:43:30 - [info] [loxone-miniserver: e42aefbc.0dfdc] connection closed 
1 | node-red | 28 Jul 14:43:32 - [info] [loxone-miniserver: e42aefbc.0dfdc] Miniserver connected (192.168.1.95:80) using token-enc 
1 | node-red | 28 Jul 14:43:32 - [error] [loxone-miniserver: e42aefbc.0dfdc] Miniserver connection error: undefined 
1 | node-red | 28 Jul 14:43:32 - [info] [loxone-miniserver: e42aefbc.0dfdc] connection closed


```

**Comment by xAPPO** [comment]
I should mention I have no loxone-miniserver node - (it is shown greyed out in palette manager) but I assume it is no longer supposed to show in the palette ? 

Your code 0.10.1
NodeRED 0.18.7 (tried both a Docker and non Docker version)
Loxone 9.3.3.26

I tried another miniserver 9.0.9.26  that has almost no CPU loading and is on the same switch as NodeRED in case that was an issue but same disconnect issues.

**Comment by codmpm** [comment]
Please give me some time for this... 

I'm currently trying to get a second miniserver to build a testenvironment for that issue.

**Comment by xAPPO** [comment]
Will do .. no problem as I have blanked out the error logs in you code for the time being..   If you would like to borrow one from me that would be OK... or I could open up a WAN port for you to access one.

**Comment by codmpm** [comment]
I think I have one on hand... let me check that and if it now works out, I will get back to you.

**Comment by codmpm** [comment]
Sorry @xAPPO, I still don't have a second miniserver to test this... did you still have the problem?

**Comment by Zrmite** [comment]
I've got the same problem, but with only one Miniserver. I try to Ping the Miniserver from my Raspberry Pi without any problems. Do you have any solution for this?

> 11 Jul 11:52:05 - [info] [loxone-miniserver:96f55419.31c62] Miniserver connected (10.100.27.62:2000) using Token-Enc
> 11 Jul 11:52:05 - [error] [loxone-miniserver:96f55419.31c62] Miniserver connection error: undefined
> 11 Jul 11:52:05 - [info] [loxone-miniserver:96f55419.31c62] connection closed
> 11 Jul 11:52:06 - [info] [loxone-miniserver:96f55419.31c62] Miniserver connected (10.100.27.62:2000) using Token-Enc
> 11 Jul 11:52:06 - [error] [loxone-miniserver:96f55419.31c62] Miniserver connection error: undefined
> 11 Jul 11:52:06 - [info] [loxone-miniserver:96f55419.31c62] connection closed
> 11 Jul 11:52:06 - [info] [loxone-miniserver:96f55419.31c62] Miniserver connected (10.100.27.62:2000) using Token-Enc
> 11 Jul 11:52:06 - [error] [loxone-miniserver:96f55419.31c62] Miniserver connection error: undefined
> 11 Jul 11:52:06 - [info] [loxone-miniserver:96f55419.31c62] connection closed
> 11 Jul 11:52:06 - [info] [loxone-miniserver:96f55419.31c62] Miniserver connected (10.100.27.62:2000) using Token-Enc
> 11 Jul 11:52:06 - [error] [loxone-miniserver:96f55419.31c62] Miniserver connection error: undefined
> 11 Jul 11:52:06 - [info] [loxone-miniserver:96f55419.31c62] connection closed
> 11 Jul 11:52:07 - [info] [loxone-miniserver:96f55419.31c62] Miniserver connected (10.100.27.62:2000) using Token-Enc
> 11 Jul 11:52:07 - [error] [loxone-miniserver:96f55419.31c62] Miniserver connection error: undefined
> 11 Jul 11:52:07 - [info] [loxone-miniserver:96f55419.31c62] connection closed
> 11 Jul 11:52:08 - [info] [loxone-miniserver:96f55419.31c62] Miniserver connected (10.100.27.62:2000) using Token-Enc
> 11 Jul 11:52:08 - [error] [loxone-miniserver:96f55419.31c62] Miniserver connection error: undefined
> 11 Jul 11:52:08 - [info] [loxone-miniserver:96f55419.31c62] connection closed
> 11 Jul 11:52:08 - [info] [loxone-miniserver:96f55419.31c62] Miniserver connected (10.100.27.62:2000) using Token-Enc
> 11 Jul 11:52:08 - [error] [loxone-miniserver:96f55419.31c62] Miniserver connection error: undefined
> 11 Jul 11:52:08 - [info] [loxone-miniserver:96f55419.31c62] connection closed
> 11 Jul 11:52:08 - [info] [loxone-miniserver:96f55419.31c62] Miniserver connected (10.100.27.62:2000) using Token-Enc
> 11 Jul 11:52:08 - [error] [loxone-miniserver:96f55419.31c62] Miniserver connection error: undefined
> 11 Jul 11:52:08 - [info] [loxone-miniserver:96f55419.31c62] connection closed
> 11 Jul 11:52:09 - [info] [loxone-miniserver:96f55419.31c62] Miniserver connected (10.100.27.62:2000) using Token-Enc
> 11 Jul 11:52:09 - [error] [loxone-miniserver:96f55419.31c62] Miniserver connection error: undefined
> 11 Jul 11:52:09 - [info] [loxone-miniserver:96f55419.31c62] connection closed

**Comment by codmpm** [comment]
Could you provide node-red, node.js and node-red-contrib-loxone version numbers?

Cheers,
Patrik

**Comment by Zrmite** [comment]
Sure!
node-red v0.20.6
node.js v11.9.0
node-red-contrib-loxone v0.10.2
Loxone v10.2.3.26
Maybe also important: I run my Node Red in a Docker Container.

**Comment by codmpm** [comment]
Hmm,

I've never used node-red in a docker container. Could you maybe test a clean Install in a VM or on your PC/Raspberry and check if the problem persists?

**Comment by Zrmite** [comment]
I connected a second Raspberry Pi with Node Red (Also in a Container) to the same Miniserver. This one has no Problem at all and stays connected while the other one still loses the connection. 
Any other ideas? Thanks!

**Comment by codmpm** [comment]
Hmm... maybe if we have more insight we can track this down.

The message is from `loxone.js`  but this only shows `error` from node-lox-ws-api.
https://github.com/codmpm/node-red-contrib-loxone/blob/15861c88d84a75d93b00092509babfe47f416c7f/loxone/loxone.js#L175

@alladdin, do you have an idea on how to get a better error message?

**Comment by Zrmite** [comment]
@codmpm @alladdin  is there any update on this issue?

**Comment by codmpm** [comment]
I tried to reach out to @alladdin but without luck.
Will debug this as soon as I got time... but currently moving to a new house and so on. Sorry, that I don't have better news.

**Comment by mbbelgium** [comment]
hi @codmpm and @xAPPO , have you allready found a solution? I stumbled on the same problem!

**Comment by codmpm** [comment]
Sorry. I've still did not hear anything from @alladdin... and my time is very limited at the moment. Hope to dive into node-lox-ws-api as soon as we've moved houses, etc.

**Comment by mbbelgium** [comment]
thanx @codmpm I'm a beginner in programmins so I don't know how to tackle the problem. But I will search... Who knows I find something

**Comment by codmpm** [comment]
Could you please test this again with `0.10.4` and have a look into the node-red log when the error occurs? 

I've added more information for the connection from node-lox-ws-api, which I've forked as @alladdin sadly did not react to any of my messages.

**Comment by codmpm** [comment]
Please check with 0.10.6, should be fixed.
