### ISSUE TITLE
Unable to set Mode on a "Intelligent Room Controller"

### ISSUE THREAD

**Issue by sushilks** [codmpm/node-red-contrib-loxone#29]
There "control Out" function does not allow for setting specific items associated with the destination device. 
i.e in my case I have the room heating/cooling controlled by "Intelligent Room Controller" which has a mode setting.
I would like node-red to be able to change the mode on this controller but it does not allow that.

**Comment by codmpm** [comment]
This lies in the underlying design of the websocket. Some items could not be set through the control-out-node. Use the webservice node instead, like the third example on the main page.

**Comment by sushilks** [comment]
Thanks that works.
