### ISSUE TITLE
Loxone node wont install or update

### ISSUE THREAD

**Issue by JAComms** [codmpm/node-red-contrib-loxone#30]
Hello

I have tried to update on a working install & install fresh on a new install and I come up with an error each time : 

"Installation of module node-red-contrib-loxone failed: version not found"

any thoughts??

My new install is on a raspberry pi and my working install is on a VM

**Comment by codmpm** [comment]
Is this still relevant? What version of nodejs and node-red are you using?

**Comment by JAComms** [comment]
issue resolved.

Thanks for getting back to me.

**Comment by codmpm** [comment]
Superb... after all, sorry for the late reply.
