### ISSUE TITLE
No events processed after Miniserver programming

### ISSUE THREAD

**Issue by andrasg** [codmpm/node-red-contrib-loxone#33]
After programming the Miniserver, the connection seems to be coming up but there are no events coming from the `loxone-control-in` node. Seems like that the loxone nodered plugin is getting into a weird state.

What logs could I have a look at?

**Comment by andrasg** [comment]
Had a look at `node-red-log`. Looks like the structure file download is not happening...

```
3 Dec 17:22:34 - [info] [loxone-miniserver:a6b98b51.f5ee5] Miniserver connected (192.168.20.244:80) using Token-Enc
3 Dec 17:22:36 - [info] [loxone-miniserver:a6b98b51.f5ee5] got structure file 2019-12-03 17:21:49
5 Dec 13:17:36 - [info] [loxone-miniserver:a6b98b51.f5ee5] connection closed
```
... lot of connection closed messages
```
5 Dec 13:18:14 - [info] [loxone-miniserver:a6b98b51.f5ee5] connection closed
5 Dec 13:18:16 - [info] [loxone-miniserver:a6b98b51.f5ee5] Miniserver connected (192.168.20.244:80) using Token-Enc
```

But there's no structure file download at the end. If I manually restart nodered, it returns back to normal:

```
5 Dec 13:20:02 - [info] Stopping flows
5 Dec 13:20:02 - [info] [mqtt-broker:605c7a1e.feaf14] Disconnected from broker: mqtt://localhost:1883
5 Dec 13:20:03 - [info] [loxone-miniserver:a6b98b51.f5ee5] connection closed
5 Dec 13:20:03 - [info] Stopped flows
5 Dec 13:20:03 - [info] Starting flows
5 Dec 13:20:03 - [info] Started flows
5 Dec 13:20:03 - [info] [mqtt-broker:605c7a1e.feaf14] Connected to broker: mqtt://localhost:1883
5 Dec 13:20:03 - [info] [loxone-miniserver:a6b98b51.f5ee5] Miniserver connected (192.168.20.244:80) using Token-Enc
5 Dec 13:20:03 - [info] [loxone-miniserver:a6b98b51.f5ee5] got structure file 2019-12-05 13:17:29
```

**Comment by codmpm** [comment]
Hey @andrasg,

first time seeing this. We currently only have a problem with #28.
What node-red, nodeJS and Miniserver version are you on?

Cheers

**Comment by andrasg** [comment]
Hey, I am on `10.3.11.25` but have been seeing this on the previous major version as well.

**Comment by codmpm** [comment]
Ok. Can someone countercheck on his installation? I can not reproduce this here..

node-red 1.0.3
nodeJS v10.17.0
miniserver 10.3 (2019.11.24)

```
0|node-red | 5 Dec 13:48:09 - [info] Flows starten
0|node-red | 5 Dec 13:48:09 - [info] Flows gestartet
0|node-red | 5 Dec 13:48:09 - [info] Server wird jetzt auf http://127.0.0.1:1880/ ausgeführt.
0|node-red | 5 Dec 13:48:09 - [info] [loxone-miniserver:3caea919.f2d03e] Miniserver connected (nodelox.codm.de:80) using Token-Enc
0|node-red | 5 Dec 13:48:10 - [info] [loxone-miniserver:3caea919.f2d03e] got structure file 2019-11-27 17:34:40
```

control-in working:

![Bildschirmfoto 2019-12-05 um 13 50 12](https://user-images.githubusercontent.com/9745239/70236919-361a0780-1766-11ea-8838-aaa35b08560f.png)

@andrasg: Did you try a full deploy? Could give some more info about your environment?

**Comment by codmpm** [comment]
@andrasg: the connection got closed two days _after_ the structure file was downloaded

```
3 Dec 17:22:36 - [info] [loxone-miniserver:a6b98b51.f5ee5] got structure file 2019-12-03 17:21:49
5 Dec 13:17:36 - [info] [loxone-miniserver:a6b98b51.f5ee5] connection closed
```

Currently I suspect something in your network and node-red-contrib-loxone not handling the disconnect correctly. Could you use an online-node to check over some time?

**Comment by andrasg** [comment]
Yes, I rebooted the miniserver on the 3rd, that's totally fine. Then I have made a program change on the miniserver on the 5th, hence the Miniserver closed the connection. This is fine as well.
`node-red-contrib-loxone` tried reconnecting (while the Miniserver was rebooting), and seemingly succeeded the connection but there were no events emitted by nodes.
The only thing unusual I have noticed was that there was no structure file after the download.

**Comment by andrasg** [comment]
@codmpm, so to sum up, my problem is not with the connection close (which is okay, as there is Miniserver programming happening) but what happens after the reconnection once the Miniserver becomes available again.

Once I "fix" the situation by restarting nodered or simply redeploying the flow, the flow works without issues for longer periods (has been running for 6 months without issue).

**Comment by andrasg** [comment]
> Did you try a full deploy? Could give some more info about your environment?

Yes, redeploying the nodered flow solves the issue, that's usually how I fix this:
1. program miniserver
2. redeploy nodered flow

Nodered: `v0.20.5`
NodeJS: `v12.13.1`
Miniserver: `10.3.11.25`

**Comment by codmpm** [comment]
Ahh, now I got you. Thanks.

As I have work to do on fixing #28, I will also have a look into this.
But it's end of the year and work is demanding it's time.

I will get back here....

**Comment by andrasg** [comment]
Sure, my issue is nothing urgent, it's something pretty easy to live with (simply restart nodered or redeploy flow, causing a restart of the plugin).
Let me know if you need anything else

**Comment by codmpm** [comment]
Please test this with 0.10.3

**Comment by andrasg** [comment]
> Please test this with 0.10.3

It doesn't seem to find the forked `node-lox-ws-api` package:
```
14 Dec 13:43:53 - [warn] [node-red-contrib-loxone/loxone] Error: Cannot find module 'node-lox-ws-api'
Require stack:
- /home/pi/.node-red/node_modules/node-red-contrib-loxone/loxone/loxone.js
- /usr/lib/node_modules/node-red/node_modules/@node-red/registry/lib/loader.js
- /usr/lib/node_modules/node-red/node_modules/@node-red/registry/lib/index.js
- /usr/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/nodes/index.js
- /usr/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/index.js
- /usr/lib/node_modules/node-red/lib/red.js
- /usr/lib/node_modules/node-red/red.js
```
and then sitting and waiting here:
```
14 Dec 13:43:53 - [info] Waiting for missing types to be registered:
14 Dec 13:43:53 - [info]  - loxone-miniserver
14 Dec 13:43:53 - [info]  - loxone-control-out
14 Dec 13:43:53 - [info]  - loxone-control-in
14 Dec 13:43:53 - [info]  - loxone-online
```

**Comment by codmpm** [comment]
Sorry, had a mistake in `package.json` referencing my local development directory. Fixed in https://github.com/codmpm/node-red-contrib-loxone/commit/2ad9c22d4ecb212d5d5752d5b7eb219c5df94c81 / `0.10.4`

Please test again.
If you get `permission denied` while installing `0.10.4` please delete `node-lox-ws-api` from `node_modules` and install again. It's a leftover symlink from the reference to my local development node-lox-ws-api.
`rm ~/.node-red/node_modules/node-lox-ws-api`

**Comment by andrasg** [comment]
Looks better. I wasn't able to repro the issue after numerous Loxone programming cycles.

Looking at the forked `node-lox-ws-api`, I don't see any nodered specifics. Would make sense to PR it back to upstream...

**Comment by codmpm** [comment]
Thought about filing a pull request... but @alladdin, the maintainer of node-lox-ws-api, did not react to any of my efforts to contact him.

I did not change anything inside node-lox-ws-api except more information on connection closing.

On the other hand in node-red-contrib-loxone there was no direct change, that could affect your problem. 
The connection status "connected" is now set _after_ the succesfull authentification and not directly after the connect when the authentification to the miniserver is not done, yet. So, this could maybe have solved your problem.
