### ISSUE TITLE
package reference

### ISSUE THREAD

**Issue by mabunixda** [codmpm/node-red-contrib-loxone#36]
Hi,

your package reference does not exist!
https://github.com/codmpm/node-red-contrib-loxone/blob/2ad9c22d4ecb212d5d5752d5b7eb219c5df94c81/package.json#L17

this blocks installation from your latest publication :-(

**Comment by codmpm** [comment]
Should not be...

> GitHub URLs
> As of version 1.1.65, you can refer to GitHub urls as just “foo”: “user/foo-project”. Just as with git URLs, a commit-ish suffix can be included. For example:

```
{
  "name": "foo",
  "version": "0.0.0",
  "dependencies": {
    "express": "expressjs/express",
    "mocha": "mochajs/mocha#4727d357ea",
    "module": "user/repo#feature\/branch"
  }
}
```
– https://docs.npmjs.com/files/package.json#github-urls

The package is located at https://github.com/codm/node-lox-ws-api and installs here without any problems. Also info's from the LoxForum state that this works.
Be sure to install `0.10.4` as I had a mistake in `0.10.3` by referencing a local path.

If you have a permission error, delete `~/.node-red/node_modules/node-lox-ws-api` and install again.

**Comment by codmpm** [comment]
I've just filed a pull request to get my changes into the published node-lox-ws-api: https://github.com/alladdin/node-lox-ws-api/pull/18

**Comment by mabunixda** [comment]
ok i was not able to access your repo previously ... may be copy&paste error.. or some docker foo problem because i install it in a docker container ;-)

**Comment by Noschvie** [comment]
Support needed : how have the statement inside a docker file be changed to get working again ?
`RUN npm install --save node-red-contrib-loxone`
Thanks!

**Comment by codmpm** [comment]
Hey @Noschvie, you need git inside your docker container as the required library is now pulled via github. Sadly @alladdin did not merge my pull request yet, to put into the npm published version.

@mabunixda could you give @Noschvie some support on how you managed to get it working again?

**Comment by mabunixda** [comment]
@Noschvie you need to generate your own dockerfile. afterwards you can add  deps:
```
FROM nodered/node-red:latest-12-minimal
USER root
RUN npm install node-red-contrib-loxone
USER node-red
```

**Comment by Noschvie** [comment]
... but this doesn't work, what seems to be wrong?
```
Step 6/13 : RUN npm install --unsafe-perm node-red-contrib-loxone
 ---> Running in 1c69775aefc8
npm ERR! code 128
npm ERR! Command failed: git clone --mirror -q git://github.com/codm/node-lox-ws-api.git /root/.npm/_cacache/tmp/git-clone-30ffe56e/.git
npm ERR! fatal: could not create leading directories of '/root/.npm/_cacache/tmp/git-clone-30ffe56e/.git'
npm ERR! 
```
