### ISSUE TITLE
nodered flow for analog in/out

### ISSUE THREAD

**Issue by elpaso666** [codmpm/node-red-contrib-loxone#38]
Hi,

I am sorry for submitting an "issue". I would like to kindly ask for flow of bi-directional analog in.

I have bought German product call ConBee from Dresden electronic, which has wonderfull ZigBee capabilities and also Deconz NodeRed contrib.

However I am wondering how to link loxone and HUE bulbs with Deconz in nodered (https://github.com/andreypopov/node-red-contrib-deconz)

thx
Jakub

**Comment by codmpm** [comment]
Sorry, this is not the place for advice on how to get flows working.

**Comment by elpaso666** [comment]
I am sorry, I am just wondering why this flow (analog IN/OUT) is not available like the other and is available only as video-proof-of-functionality.

I have already found https://gist.github.com/sstroot/a2be61a889a6e6712fa0591ab1a69e35 which is exactly what I was looking for.

thx again and have great 2020
