### ISSUE TITLE
not able to install the contrib on 2nd RPI

### ISSUE THREAD

**Issue by elpaso666** [codmpm/node-red-contrib-loxone#39]
Hi,

I am getting following error when trying to install on another RPI.

can you please help.

thank you!

sudo cat /root/.npm/_logs/2020-01-01T20_30_52_703Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/usr/bin/node',
1 verbose cli   '/usr/bin/npm',
1 verbose cli   'install',
1 verbose cli   'node-red-contrib-loxone'
1 verbose cli ]
2 info using npm@6.13.4
3 info using node@v12.14.0
4 verbose npm-session b5fec69c4c8b0b9e
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 200 https://registry.npmjs.org/node-red-contrib-loxone 712ms
8 silly pacote tag manifest for node-red-contrib-loxone@latest fetched in 807ms
9 timing stage:loadCurrentTree Completed in 4673ms
10 silly install loadIdealTree
11 silly install cloneCurrentTreeToIdealTree
12 timing stage:loadIdealTree:cloneCurrentTree Completed in 46ms
13 silly install loadShrinkwrap
14 timing stage:loadIdealTree:loadShrinkwrap Completed in 2263ms
15 silly install loadAllDepsIntoIdealTree
16 silly resolveWithNewModule node-red-contrib-loxone@0.10.4 checking installable status
17 silly fetchPackageMetaData error for node-lox-ws-api@github:codm/node-lox-ws-api Error while executing:
17 silly fetchPackageMetaData undefined ls-remote -h -t ssh://git@github.com/codm/node-lox-ws-api.git
17 silly fetchPackageMetaData
17 silly fetchPackageMetaData
17 silly fetchPackageMetaData spawn git ENOENT
18 timing stage:rollbackFailedOptional Completed in 5ms
19 timing stage:runTopLevelLifecycles Completed in 7191ms
20 silly saveTree node-red-project@0.0.1
20 silly saveTree ├── node-red-contrib-combine@1.8.1
20 silly saveTree ├─┬ node-red-contrib-deconz@1.1.9
20 silly saveTree │ ├── events@3.0.0
20 silly saveTree │ ├── multiple-select@1.5.2
20 silly saveTree │ ├─┬ request@2.88.0
20 silly saveTree │ │ ├── aws-sign2@0.7.0
20 silly saveTree │ │ ├── aws4@1.9.0
20 silly saveTree │ │ ├── caseless@0.12.0
20 silly saveTree │ │ ├─┬ combined-stream@1.0.8
20 silly saveTree │ │ │ └── delayed-stream@1.0.0
20 silly saveTree │ │ ├── extend@3.0.2
20 silly saveTree │ │ ├── forever-agent@0.6.1
20 silly saveTree │ │ ├─┬ form-data@2.3.3
20 silly saveTree │ │ │ ├── asynckit@0.4.0
20 silly saveTree │ │ │ └─┬ mime-types@2.1.25
20 silly saveTree │ │ │   └── mime-db@1.42.0
20 silly saveTree │ │ ├─┬ har-validator@5.1.3
20 silly saveTree │ │ │ ├─┬ ajv@6.10.2
20 silly saveTree │ │ │ │ ├── fast-deep-equal@2.0.1
20 silly saveTree │ │ │ │ ├── fast-json-stable-stringify@2.1.0
20 silly saveTree │ │ │ │ ├── json-schema-traverse@0.4.1
20 silly saveTree │ │ │ │ └─┬ uri-js@4.2.2
20 silly saveTree │ │ │ │   └── punycode@2.1.1
20 silly saveTree │ │ │ └── har-schema@2.0.0
20 silly saveTree │ │ ├─┬ http-signature@1.2.0
20 silly saveTree │ │ │ ├── assert-plus@1.0.0
20 silly saveTree │ │ │ ├─┬ jsprim@1.4.1
20 silly saveTree │ │ │ │ ├── extsprintf@1.3.0
20 silly saveTree │ │ │ │ ├── json-schema@0.2.3
20 silly saveTree │ │ │ │ └─┬ verror@1.10.0
20 silly saveTree │ │ │ │   └── core-util-is@1.0.2
20 silly saveTree │ │ │ └─┬ sshpk@1.16.1
20 silly saveTree │ │ │   ├─┬ asn1@0.2.4
20 silly saveTree │ │ │   │ └── safer-buffer@2.1.2
20 silly saveTree │ │ │   ├─┬ bcrypt-pbkdf@1.0.2
20 silly saveTree │ │ │   │ └── tweetnacl@0.14.5
20 silly saveTree │ │ │   ├── dashdash@1.14.1
20 silly saveTree │ │ │   ├─┬ ecc-jsbn@0.1.2
20 silly saveTree │ │ │   │ └── jsbn@0.1.1
20 silly saveTree │ │ │   ├── getpass@0.1.7
20 silly saveTree │ │ │   ├── jsbn@0.1.1
20 silly saveTree │ │ │   ├── safer-buffer@2.1.2
20 silly saveTree │ │ │   └── tweetnacl@0.14.5
20 silly saveTree │ │ ├── is-typedarray@1.0.0
20 silly saveTree │ │ ├── isstream@0.1.2
20 silly saveTree │ │ ├── json-stringify-safe@5.0.1
20 silly saveTree │ │ ├── mime-types@2.1.25
20 silly saveTree │ │ ├── oauth-sign@0.9.0
20 silly saveTree │ │ ├── performance-now@2.1.0
20 silly saveTree │ │ ├── qs@6.5.2
20 silly saveTree │ │ ├── safe-buffer@5.1.2
20 silly saveTree │ │ ├─┬ tough-cookie@2.4.3
20 silly saveTree │ │ │ ├── psl@1.6.0
20 silly saveTree │ │ │ └── punycode@1.4.1
20 silly saveTree │ │ ├── tunnel-agent@0.6.0
20 silly saveTree │ │ └── uuid@3.3.3
20 silly saveTree │ └── ws@7.2.1
20 silly saveTree ├─┬ node-red-contrib-homekit-bridged@0.8.0
20 silly saveTree │ ├── child_process@1.0.2
20 silly saveTree │ ├─┬ debug@4.1.1
20 silly saveTree │ │ └── ms@2.1.2
20 silly saveTree │ ├── fs@0.0.2
20 silly saveTree │ ├─┬ hap-nodejs@0.5.0
20 silly saveTree │ │ ├─┬ bonjour-hap@3.5.4
20 silly saveTree │ │ │ ├── array-flatten@2.1.2
20 silly saveTree │ │ │ ├─┬ deep-equal@1.1.1
20 silly saveTree │ │ │ │ ├── is-arguments@1.0.4
20 silly saveTree │ │ │ │ ├── is-date-object@1.0.2
20 silly saveTree │ │ │ │ ├─┬ is-regex@1.0.5
20 silly saveTree │ │ │ │ │ └─┬ has@1.0.3
20 silly saveTree │ │ │ │ │   └── function-bind@1.1.1
20 silly saveTree │ │ │ │ ├── object-is@1.0.2
20 silly saveTree │ │ │ │ ├── object-keys@1.1.1
20 silly saveTree │ │ │ │ └─┬ regexp.prototype.flags@1.3.0
20 silly saveTree │ │ │ │   ├── define-properties@1.1.3
20 silly saveTree │ │ │ │   └─┬ es-abstract@1.17.0
20 silly saveTree │ │ │ │     ├─┬ es-to-primitive@1.2.1
20 silly saveTree │ │ │ │     │ ├── is-callable@1.1.5
20 silly saveTree │ │ │ │     │ └─┬ is-symbol@1.0.3
20 silly saveTree │ │ │ │     │   └── has-symbols@1.0.1
20 silly saveTree │ │ │ │     ├── has-symbols@1.0.1
20 silly saveTree │ │ │ │     ├── is-callable@1.1.5
20 silly saveTree │ │ │ │     ├── object-inspect@1.7.0
20 silly saveTree │ │ │ │     ├── object.assign@4.1.0
20 silly saveTree │ │ │ │     ├── string.prototype.trimleft@2.1.1
20 silly saveTree │ │ │ │     └── string.prototype.trimright@2.1.1
20 silly saveTree │ │ │ ├── dns-equal@1.0.0
20 silly saveTree │ │ │ ├─┬ dns-txt@2.0.2
20 silly saveTree │ │ │ │ └── buffer-indexof@1.1.1
20 silly saveTree │ │ │ ├── multicast-dns-service-types@1.1.0
20 silly saveTree │ │ │ └─┬ multicast-dns@7.2.0
20 silly saveTree │ │ │   ├─┬ dns-packet@4.2.0
20 silly saveTree │ │ │   │ └── ip@1.1.5
20 silly saveTree │ │ │   └── thunky@1.1.0
20 silly saveTree │ │ ├── buffer-shims@1.0.0
20 silly saveTree │ │ ├─┬ debug@2.6.9
20 silly saveTree │ │ │ └── ms@2.0.0
20 silly saveTree │ │ ├── decimal.js@7.5.1
20 silly saveTree │ │ ├── fast-srp-hap@1.0.1
20 silly saveTree │ │ ├── ip@1.1.5
20 silly saveTree │ │ ├─┬ node-persist@0.0.11
20 silly saveTree │ │ │ ├─┬ mkdirp@0.5.1
20 silly saveTree │ │ │ │ └── minimist@0.0.8
20 silly saveTree │ │ │ └── q@1.1.2
20 silly saveTree │ │ └── tweetnacl@1.0.1
20 silly saveTree │ ├── ip@1.1.5
20 silly saveTree │ ├── net@1.0.2
20 silly saveTree │ └── os@0.1.1
20 silly saveTree ├── node-red-contrib-loxone@0.10.4
20 silly saveTree ├── node-red-contrib-play-audio@2.4.0
20 silly saveTree ├── node-red-node-pi-gpio@1.0.6
20 silly saveTree ├── node-red-node-ping@0.1.0
20 silly saveTree ├── node-red-node-random@0.1.4
20 silly saveTree ├─┬ node-red-node-serialport@0.10.0
20 silly saveTree │ └─┬ serialport@8.0.6
20 silly saveTree │   ├─┬ @serialport/binding-mock@8.0.6
20 silly saveTree │   │ └── @serialport/binding-abstract@8.0.6
20 silly saveTree │   ├─┬ @serialport/bindings@8.0.6
20 silly saveTree │   │ ├─┬ @serialport/parser-readline@8.0.6
20 silly saveTree │   │ │ └── @serialport/parser-delimiter@8.0.6
20 silly saveTree │   │ ├─┬ bindings@1.5.0
20 silly saveTree │   │ │ └── file-uri-to-path@1.0.0
20 silly saveTree │   │ ├── nan@2.14.0
20 silly saveTree │   │ └─┬ prebuild-install@5.3.3
20 silly saveTree │   │   ├── detect-libc@1.0.3
20 silly saveTree │   │   ├── expand-template@2.0.3
20 silly saveTree │   │   ├── github-from-package@0.0.0
20 silly saveTree │   │   ├── minimist@1.2.0
20 silly saveTree │   │   ├── napi-build-utils@1.0.1
20 silly saveTree │   │   ├─┬ node-abi@2.13.0
20 silly saveTree │   │   │ └── semver@5.7.1
20 silly saveTree │   │   ├── noop-logger@0.1.1
20 silly saveTree │   │   ├─┬ npmlog@4.1.2
20 silly saveTree │   │   │ ├─┬ are-we-there-yet@1.1.5
20 silly saveTree │   │   │ │ ├── delegates@1.0.0
20 silly saveTree │   │   │ │ └─┬ readable-stream@2.3.6
20 silly saveTree │   │   │ │   ├── inherits@2.0.4
20 silly saveTree │   │   │ │   ├── isarray@1.0.0
20 silly saveTree │   │   │ │   ├── process-nextick-args@2.0.1
20 silly saveTree │   │   │ │   ├── string_decoder@1.1.1
20 silly saveTree │   │   │ │   └── util-deprecate@1.0.2
20 silly saveTree │   │   │ ├── console-control-strings@1.1.0
20 silly saveTree │   │   │ ├─┬ gauge@2.7.4
20 silly saveTree │   │   │ │ ├── aproba@1.2.0
20 silly saveTree │   │   │ │ ├── has-unicode@2.0.1
20 silly saveTree │   │   │ │ ├── object-assign@4.1.1
20 silly saveTree │   │   │ │ ├── signal-exit@3.0.2
20 silly saveTree │   │   │ │ ├─┬ string-width@1.0.2
20 silly saveTree │   │   │ │ │ ├── code-point-at@1.1.0
20 silly saveTree │   │   │ │ │ ├─┬ is-fullwidth-code-point@1.0.0
20 silly saveTree │   │   │ │ │ │ └── number-is-nan@1.0.1
20 silly saveTree │   │   │ │ │ └─┬ strip-ansi@3.0.1
20 silly saveTree │   │   │ │ │   └── ansi-regex@2.1.1
20 silly saveTree │   │   │ │ ├── strip-ansi@3.0.1
20 silly saveTree │   │   │ │ └── wide-align@1.1.3
20 silly saveTree │   │   │ └── set-blocking@2.0.0
20 silly saveTree │   │   ├─┬ pump@3.0.0
20 silly saveTree │   │   │ ├─┬ end-of-stream@1.4.4
20 silly saveTree │   │   │ │ └─┬ once@1.4.0
20 silly saveTree │   │   │ │   └── wrappy@1.0.2
20 silly saveTree │   │   │ └── once@1.4.0
20 silly saveTree │   │   ├─┬ rc@1.2.8
20 silly saveTree │   │   │ ├── deep-extend@0.6.0
20 silly saveTree │   │   │ ├── ini@1.3.5
20 silly saveTree │   │   │ └── strip-json-comments@2.0.1
20 silly saveTree │   │   ├─┬ simple-get@3.1.0
20 silly saveTree │   │   │ ├─┬ decompress-response@4.2.1
20 silly saveTree │   │   │ │ └── mimic-response@2.0.0
20 silly saveTree │   │   │ └── simple-concat@1.0.0
20 silly saveTree │   │   ├─┬ tar-fs@2.0.0
20 silly saveTree │   │   │ ├── chownr@1.1.3
20 silly saveTree │   │   │ └─┬ tar-stream@2.1.0
20 silly saveTree │   │   │   ├─┬ bl@3.0.0
20 silly saveTree │   │   │   │ └── readable-stream@3.4.0
20 silly saveTree │   │   │   ├── fs-constants@1.0.0
20 silly saveTree │   │   │   └── readable-stream@3.4.0
20 silly saveTree │   │   └── which-pm-runs@1.0.0
20 silly saveTree │   ├── @serialport/parser-byte-length@8.0.6
20 silly saveTree │   ├── @serialport/parser-cctalk@8.0.6
20 silly saveTree │   ├── @serialport/parser-delimiter@8.0.6
20 silly saveTree │   ├── @serialport/parser-readline@8.0.6
20 silly saveTree │   ├── @serialport/parser-ready@8.0.6
20 silly saveTree │   ├── @serialport/parser-regex@8.0.6
20 silly saveTree │   └── @serialport/stream@8.0.6
20 silly saveTree └── node-red-node-smooth@0.1.2
21 verbose stack Error: spawn git ENOENT
21 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
21 verbose stack     at onErrorNT (internal/child_process.js:456:16)
21 verbose stack     at processTicksAndRejections (internal/process/task_queues.js:80:21)
22 verbose cwd /home/pi/.node-red
23 verbose Linux 4.19.75-v7+
24 verbose argv "/usr/bin/node" "/usr/bin/npm" "install" "node-red-contrib-loxone"
25 verbose node v12.14.0
26 verbose npm  v6.13.4
27 error code ENOENT
28 error syscall spawn git
29 error path git
30 error errno ENOENT
31 error enoent Error while executing:
31 error enoent undefined ls-remote -h -t ssh://git@github.com/codm/node-lox-ws-api.git
31 error enoent
31 error enoent
31 error enoent spawn git ENOENT
32 error enoent This is related to npm not being able to find a file.
33 verbose exit [ 1, true ]

**Comment by elpaso666** [comment]
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/usr/bin/node',
1 verbose cli   '/usr/bin/npm',
1 verbose cli   'install',
1 verbose cli   'node-red-contrib-loxone'
1 verbose cli ]
2 info using npm@6.13.4
3 info using node@v12.14.0
4 verbose npm-session b5fec69c4c8b0b9e
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 200 https://registry.npmjs.org/node-red-contrib-loxone 712ms
8 silly pacote tag manifest for node-red-contrib-loxone@latest fetched in 807ms
9 timing stage:loadCurrentTree Completed in 4673ms
10 silly install loadIdealTree
11 silly install cloneCurrentTreeToIdealTree
12 timing stage:loadIdealTree:cloneCurrentTree Completed in 46ms
13 silly install loadShrinkwrap
14 timing stage:loadIdealTree:loadShrinkwrap Completed in 2263ms
15 silly install loadAllDepsIntoIdealTree
16 silly resolveWithNewModule node-red-contrib-loxone@0.10.4 checking installable status
17 silly fetchPackageMetaData error for node-lox-ws-api@github:codm/node-lox-ws-api Error while executing:
17 silly fetchPackageMetaData undefined ls-remote -h -t ssh://git@github.com/codm/node-lox-ws-api.git
17 silly fetchPackageMetaData
17 silly fetchPackageMetaData
17 silly fetchPackageMetaData spawn git ENOENT
18 timing stage:rollbackFailedOptional Completed in 5ms
19 timing stage:runTopLevelLifecycles Completed in 7191ms

**Comment by codmpm** [comment]
Please install `git` on the pi, as since `0.10.3` the needed `node-lox-ws-api` is pulled via git.

**Comment by elpaso666** [comment]
thank you and sorry not being able to read log correctly :)
