### ISSUE TITLE
Intermittent close timeout when deploying

### ISSUE THREAD

**Issue by andrasg** [codmpm/node-red-contrib-loxone#40]
Since updating to `v0.10.4` I am seeing this error quite frequently when deploying node:

```
9 Jan 17:39:03 - [info] Stopping flows
9 Jan 17:39:03 - [info] [mqtt-broker:605c7a1e.feaf14] Disconnected from broker: mqtt://localhost:1883
9 Jan 17:39:18 - [error] [loxone-miniserver:a6b98b51.f5ee5] Error stopping node: Close timed out
9 Jan 17:39:18 - [info] Stopped flows
```

Not a huge issue or majorly blocking, just reporting it. Any way I could debug it further?

**Comment by codmpm** [comment]
Hey @andrasg, sorry for the delay. Just fixing some stuff in node-red-contrib-loxone currently.

I can't find `Close timed out` anywhere in node-red-contrib-loxone and all it's dependencys.

Could you give me more info on your environment (node version, etc.) and rule out that you have some sort of connectivity issued?

**Comment by codmpm** [comment]
Please check with 0.10.6, should be fixed.

**Comment by ludekvodicka** [comment]
Hello @codmpm ,
just testing the latest v 0.10.10 and receiving this error message too.

23. 9. 2020 9:30:57node: 33d50a38.be2cc6
msg : string[36]
"Error stopping node: Close timed out"

It happens when deploying and it delays deploy for ~20 sec.
