### ISSUE TITLE
Getting the structure file or objects from it

### ISSUE THREAD

**Issue by davidwallis** [codmpm/node-red-contrib-loxone#43]
Hi,

I'm trying to build some processing for messages using node-red - but I would like to programatically extract objects from the structure file - such as rooms. I know that the structure file is got - but are these objects exposed anywhere or am I going to have to pull the structure file myself and process it?

Thanks

David

**Comment by codmpm** [comment]
Hey David,

no, the rooms are currently not exposed. Only used internally to show the dropdowns inside the node.
But you can simply parse the http://<ip-miniserver>data/LoxAPP3.json using an http-request-node and the json-node.

**Comment by davidwallis** [comment]
thanks!
