### ISSUE TITLE
unable to install in nodered

### ISSUE THREAD

**Issue by mbogaerts** [codmpm/node-red-contrib-loxone#47]
tis error is thrown during installation:
ERR! git clone git@github.com:github:codm/node-lox-ws-api

**Comment by codmpm** [comment]
https://github.com/codmpm/node-red-contrib-loxone/issues/39#issuecomment-570082458

**Comment by mbogaerts** [comment]
Git is installed
stil does not work for me
$ git clone git@github.com:github:codm/node-lox-ws-api
Cloning into 'node-lox-ws-api'...
fatal: remote error:
   is not a valid repository name
  Email support@github.com for help

git clone git@github.com:codm/node-lox-ws-api does work however iff cloned manually

**Comment by codmpm** [comment]
Please check your installed git version. At least `1.1.65` is needed...

See https://github.com/codmpm/node-red-contrib-loxone/issues/36#issuecomment-566043086

**Comment by mbogaerts** [comment]
> Please check your installed git version. At least `1.1.65` is needed...
> 
> [#36 (comment)](https://github.com/codmpm/node-red-contrib-loxone/issues/36#issuecomment-566043086)

pi@raspberrypi:~/.node-red $ git version
git version 2.11.0

**Comment by codmpm** [comment]
Ok. Then please provide a full error log regarding the error together with your npm and nodejs version.
Also please check the rights in `~/.node-red`. Maybe these are messed up while doing some installation as root.

**Comment by mbogaerts** [comment]
npm 1.4.21
nodejs v8.11.1
pi@raspberrypi:~/.node-red $ npm i node-red-contrib-loxone
(node:4449) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
npm WARN package.json node-red-contrib-ds18b20-sensor@1.3.6 license should be a valid SPDX license expression
npm ERR! git clone git@github.com:github:codm/node-lox-ws-api Cloning into bare repository '/home/pi/.npm/_git-remotes/git-github-com-github-codm-node-lox-ws-api-0e137cfe'...
npm ERR! git clone git@github.com:github:codm/node-lox-ws-api fatal: remote error:
npm ERR! git clone git@github.com:github:codm/node-lox-ws-api    is not a valid repository name
npm ERR! git clone git@github.com:github:codm/node-lox-ws-api   Email support@github.com for help
npm ERR! notarget No compatible version found: node-lox-ws-api@'github:codm/node-lox-ws-api'
npm ERR! notarget Valid install targets:
npm ERR! notarget ["0.1.0","0.1.1","0.2.0","0.2.1","0.2.2","0.2.3","0.2.4","0.2.5","0.2.6","0.2.7","0.2.8","0.2.9","0.3.0","0.3.1","0.3.2","0.3.3","0.3.4","0.4.0","0.4.1","0.4.2","0.4.3","0.4.4","0.4.5"]
npm ERR! notarget
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! System Linux 4.14.98-v7+
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "i" "node-red-contrib-loxone"
npm ERR! cwd /home/pi/.node-red
npm ERR! node -v v8.11.1
npm ERR! npm -v 1.4.21
npm ERR! code ETARGET
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /home/pi/.node-red/npm-debug.log
npm ERR! not ok code 0
pi@raspberrypi:~/.node-red $

rights are being checked

**Comment by codmpm** [comment]
Please install node-red-contrib-loxone using "Manage Palette" from the node-red menu. Before that delete `~/.node-red/node-red-contrib-loxone` if it exists.

Also check the permissions of `~/.npm/`.

**Comment by mbogaerts** [comment]
i'll try... however thats where is started and ended up trying it manually
keep you informed

**Comment by mbogaerts** [comment]
Please install node-red-contrib-loxone using "Manage Palette" from the node-red menu. Before that delete ~/.node-red/node-red-contrib-loxone if it exists.
> Did not exist
Also check the permissions of ~/.npm/.
pi user has rw 

all same result...

why is the :github in clone url present? 
npm ERR! git clone git@github.com:github:codm/node-lox-ws-api is not a valid repository name
>> git clone git@github.com >> :github << :codm/node-lox-ws-api

**Comment by codmpm** [comment]
I don't know, never came over that as it always worked for me.

Could you maybe try a frehs node-red install in an virtual machine or something and follow the guide at https://nodered.org/docs/getting-started ?

**Comment by mbogaerts** [comment]
Reinstalled the PI (switched to balena for deployment now) and its all working now.
