### ISSUE TITLE
Add online/offline node

### ISSUE THREAD

**Issue by SteeveK** [codmpm/node-red-contrib-loxone#5]
Hello,
First of all, excuse my english i'm french...
I wanted to say that your  node-red-contrib-loxone IS SIMPLY GENIAL !!!! Finally I waited for this for a long time, thank you, thank you !!!
I have nevertheless a problem with weather service, if I want to recover a loxone value, NODE-RED plant ...
Thank you for your help...
NODE-RED 16.2
NODEJS v6.10.1

**Comment by codmpm** [comment]
Hi Steeve,

Thank you! At the moment `weatherServer` is not parsed from the structure file at all. See the here `http://<ip-of-miniserver>/data/LoxAPP3.json`. The documentation of the structure file could be found here: https://www.loxone.com/dede/wp-content/uploads/sites/2/2016/08/loxone-structure-file.pdf?x48792

Could you reproduce the crash? What happens on the miniserver side and could you give me a screenhot of your flow? On which control/state did you hook the input node?

I'm not sure how the miniserver publishes weather-data over the websocket API. Could you manage to get what you want with the new webservice-node?

Cheers,
Patrik

**Comment by SteeveK** [comment]
Hello and thanks.
Ok...
Somes photos in this mail...
The miniserver don't crash, only node-red...

With the webservice-node its ok, thANKS.

A new question : the webservice connects to the websocket connection to read infos or connects directly on the mini-server ?

Have you also a solution to now when the miniserver reboots ? 

Thanks.

-----Message d'origine-----
De : Patrik Mayer [mailto:notifications@github.com] 
Envoyé : jeudi 23 mars 2017 15:19
À : codmpm/node-red-contrib-loxone <node-red-contrib-loxone@noreply.github.com>
Cc : STEEVE KELLER <steeve@keller-troiano.fr>; Author <author@noreply.github.com>
Objet : Re: [codmpm/node-red-contrib-loxone] LOXONE-METEO CRASCH NODE-RED (#5)

Hi Steeve,

Thank you! At the moment weatherServer is not parsed from the structure file at all. See the here http://<ip-of-miniserver>/data/LoxAPP3.json.

Could you reproduce the crash? What happens on the miniserver side and could you give me a screenhot of your flow?

I'm not sure how the miniserver publishes weather-data over the websocket API. Could you manage to get what you want with the new webservice-node?

Cheers,
Patrik

**Comment by codmpm** [comment]
Can't see the fotos, please add them on github by drag & drop.

 > A new question : the webservice connects to the websocket connection to read infos or connects directly on the mini-server ?

The webservice node uses the existing websocket connection. Simply read the documentation inside the node and here on github.

The connection is managed by the underlying node-lox-ws-api which tries to reconnect on rebooting the miniserver.

**Comment by SteeveK** [comment]
Ok and manuel thanks...
I will post the photos on github

Hop CAN i use the node ws LOx api Inde node RED ?

For exemple if the mini server reboot the value is 0 and the mini server is alive the value is 1...

Thanks

Envoy? de mon iPhone

Le 23 mars 2017 ? 20:20, Patrik Mayer <notifications@github.com<mailto:notifications@github.com>> a ?crit :


Can't see the fotos, please add them on github by drag & drop.

A new question : the webservice connects to the websocket connection to read infos or connects directly on the mini-server ?

The webservice node uses the existing websocket connection. Simply read the documentation inside the node and here on github.

The connection is managed by the underlying node-ws-lox-api which tries to reconnect on rebooting the miniserver.

-

**Comment by codmpm** [comment]
Sorry, that I do not understand you well.

If you wan't to know if the miniserver is online, simply use the http://flows.nodered.org/node/node-red-node-ping

**Comment by SteeveK** [comment]
Thanks a lot...
Excuse me for my horrible english...

I have used node red ping but i m looking for instant messages like error, reboot, update notifications through LOXONE websockets...

Do you think its possible ?

Envoy? de mon iPhone

Le 23 mars 2017 ? 21:02, Patrik Mayer <notifications@github.com<mailto:notifications@github.com>> a ?crit :


Sorry, that I do not understand you well.

If you wan't to know if the miniserver is online, simply use the http://flows.nodered.org/node/node-red-node-ping

-

**Comment by codmpm** [comment]
I think this could be possible if I fire an event from ne node, when a disconnect is detected.

Have to discuss this...

**Comment by codmpm** [comment]
I will add an online/offline node...

**Comment by SteeveK** [comment]
Many many thanks !!!!! :-))

Envoy? de mon iPhone

Le 24 mars 2017 ? 18:30, Patrik Mayer <notifications@github.com<mailto:notifications@github.com>> a ?crit :


I will add an online/offline node...

-

**Comment by SteeveK** [comment]
You are great !!!
I will tell about to LOXONE...
Its fantastic !!!

Envoy? de mon iPhone

Le 24 mars 2017 ? 18:30, Patrik Mayer <notifications@github.com<mailto:notifications@github.com>> a ?crit :


I will add an online/offline node...

-
