### ISSUE TITLE
Keepalive node always retuning 0

### ISSUE THREAD

**Issue by Drahos-X** [codmpm/node-red-contrib-loxone#52]
The **keepalive** **node** is always returning 0 in the new version 0.10.6.

**Comment by codmpm** [comment]
Thanks for pointing out. @codmdu, could you check?

**Comment by Drahos-X** [comment]
Sure, but what should I check?

**Comment by codmpm** [comment]
@codmdu should check... the programmer who reworked the keepalive cause of the reconnecting issues :-)

**Comment by Drahos-X** [comment]
Understood :-)
If I can help to test something, just let me know.

**Comment by codmpm** [comment]
Fixed in https://github.com/codm/node-lox-ws-api/releases/tag/0.4.5-bugfix2 - should be in `0.10.7` soon.

**Comment by codmpm** [comment]
Fixed in `0.10.7` which is already released, but flows.nodered.org does not have it yet.

**Comment by Drahos-X** [comment]
Everything is OK now. Thanks for quick fixing.
