### ISSUE TITLE
Race condition + fix

### ISSUE THREAD

**Issue by sebastienfouss** [codmpm/node-red-contrib-loxone#54]
Hi,

There seems to be a race condition in loxone.js, mostly visible when using node-red as a docker container.

More precisely, it might happen that a control command is sent (send_control_command) although the structure file has not been received yet by the node.

I would suggest to move the following lines:
```
node.connected = true;
node.setConnectionStatusMsg("green", "connected", "dot");
sendOnlineNodeMsg(true, config.id);
```

from 
`client.on('authorized', function () {`
to
`client.on('get_structure_file', function (data) {`

**Comment by codmpm** [comment]
Will be in `0.10.9`

**Comment by codmpm** [comment]
`0.10.9` published on npm, should be installable in the next minutes...
