### ISSUE TITLE
WebService not sending request anymore

### ISSUE THREAD

**Issue by FrankVDL2471** [codmpm/node-red-contrib-loxone#61]
Hello,

I've setup up a webservice node to send information from an MQTT bus to my Loxone MiniServer

![image](https://user-images.githubusercontent.com/24573204/105886688-fcabf780-600a-11eb-9953-cc6d401e8b59.png)

When I tried the same request in postman it works fine, but looking at the live view in Loxone Config nothing seems to comming in.

Is there a way to log what happens or to see why nothing is been send ?

Kind Regards
Frank

**Comment by codmdu** [comment]
Hi @FrankVDL2471 do you still have this issue ?
I can't reproduce this issue, its working fine for my test case.
![Bildschirmfoto 2021-04-21 um 13 12 47](https://user-images.githubusercontent.com/47142661/115545181-ca293800-a2a3-11eb-9a45-3f9370e49230.png)
![Bildschirmfoto 2021-04-21 um 13 12 19](https://user-images.githubusercontent.com/47142661/115545183-cac1ce80-a2a3-11eb-9cb6-db5b37ca6ecf.png)


Whats the payload of `msg` in your case ?
