### ISSUE TITLE
Missing "do not use" category and room 

### ISSUE THREAD

**Issue by KingAndi** [codmpm/node-red-contrib-loxone#63]
A great project, working all fine, but I have an small issue:

If I have an element in Loxone with any Category or Room (including "not assigned") everyting is working fine. But I also want to use "do not use" elements. This are elements that I use for communication between node-red and loxone miniserver but which I don't want to show in the App or on the Loxone Webinterface.

![image](https://user-images.githubusercontent.com/31312933/112300644-5e01e700-8c99-11eb-9c3a-2b3eceef8825.png)

Only the "not assigned" (in german "Nicht zugeordnet") is visible. But "do not used" (in german "Nicht verwenden") ist not available.
![image](https://user-images.githubusercontent.com/31312933/112300776-81c52d00-8c99-11eb-95c4-68faae319a1c.png)

I don't know if this is an extra feature or an bug...

Thank's a lot!

**Comment by codmpm** [comment]
Hey @KingAndi,

sadly the loxone websocket does not show items which are in the both categories.
node-red-contrib-loxone has no way to see them.

See the readme und caveats: https://github.com/codmpm/node-red-contrib-loxone#caveats

> Events can only be generated by control-in and the controls have to be visible to show up in the node. Well, this is not a caveat as it lays in the design of Loxone's websocket. We can only come around this if Loxone add's a "websocket" checkmark to the controls in Loxone-Config. Also controls will not be shown if you put them in room "unused" and category "unused", albeit they are marked "visible".

Cheers,
Patrik

**Comment by KingAndi** [comment]
Hey Patrik!

Thanks a lot for you very fast response!

But i tried it. If I first set an other category  (e.g. "not assigned") and connect it with the node it works fine.
![image](https://user-images.githubusercontent.com/31312933/112316060-0a989480-8cab-11eb-97fd-37fe2640730f.png)
After this I change the "not assigned" in loxone config into "do not use" it continues working, but in the Properties dialog of node-red the room and category is empty and so the control is not visible any more....
![image](https://user-images.githubusercontent.com/31312933/112316447-67944a80-8cab-11eb-9b6f-0aadc155f629.png)

I also had a look into the LoxApp3.json file. the elements are still there visible. 

Maybe you could fix it this way, that after opening the editing dialog the content of the control should stay if the room and category is unknown: (maybe a 0 UUID should be visible for room and category -> zero UUID="do not use", i tried it)

Bye Andi

**Comment by codmpm** [comment]
Oh, you are right. That should work. My last info was as I stated. We only display what's in the LoxApp3.json file.
Will have a look as soon as I have time.

**Comment by KingAndi** [comment]
Hallo Patrik!

Perfect, you are great!
Another question: Do you speak german? - I have another idea to discuss, but my english is not so good, so i want to talk in german...

**Comment by codmpm** [comment]
Yes, I speak german. Hit me up on the node-red slack, the wled discord or blog@allgeek.de.

**Comment by codmpm** [comment]
Ok, @codmdu had a look into this. Sadly this is not solvable.

Internally the node saves the `uuid` of the element of loxone. So, if you can select it while it is in "not assigned" (or "Living Room", "Bedroom", etc.) it can see the `uuid` and register it's event.

When you change the element in loxone to "do not use", it is no longer represented in `LoxApp3.json` thus can not be seen in node-red-contrib-loxone. 
As the uuid is still present, everything should work. But we don't have any, let's say metadata, for the uuid anymore...
Loxone simply does not show elements that are in "do not use" via the `LoxApp3.json`.

Cheers,
Patrik

---

We've just had an idea.... investigating.

**Comment by codmpm** [comment]
![Bildschirmfoto 2021-04-21 um 12 40 58](https://user-images.githubusercontent.com/9745239/115541059-fa220c80-a29e-11eb-89c3-9cd8efb1add6.png)

We've added an info on what is happeing with control's that are in room and category "Do not use".
Hope that helps 👍🏻
