### ISSUE TITLE
Controls not loaded from Miniserver

### ISSUE THREAD

**Issue by straussmarkus** [codmpm/node-red-contrib-loxone#83]
Today I setup up a new instance of node-red because I moved it to another server.

I then re-imported all my flows and I had troubles to make the connection to the miniserver work again. Got the same messages as already seen in the other issues (permanent reconnect, etc.). However, I could resolve this by deleting the user in Loxone Config and re-creating it.

In node-red it now shows as connnected and says "got miniserver structure".
All the categories and rooms are here. But all of the devices are missing. No matter what I do, I cannot select anything. The imported flows just contain a generated name/identifier for the control and don't work either.

![image](https://github.com/codmpm/node-red-contrib-loxone/assets/116552533/f4d30616-a1ed-4069-baff-2dfd91459282)

![image](https://github.com/codmpm/node-red-contrib-loxone/assets/116552533/2aa8b3d5-711d-466e-b037-9ff63fac1d63)

![image](https://github.com/codmpm/node-red-contrib-loxone/assets/116552533/329b0a75-5acb-4c3a-ae8d-7302a5a4dffe)

![image](https://github.com/codmpm/node-red-contrib-loxone/assets/116552533/a14ec8cd-7361-4323-8e10-2e308a0619d0)

Any idea why this happens?

Running node-red-contrib-loxone 0.10.13
Node-RED 3.1.9

**Comment by codmpm** [comment]
Hey Markus,

I just installed a new instance last week with node-red `3.1.9` without problems. Did not have ot recreate the user on the miniserver and get every data point.

Could you maybe retry with a not-imported node?

**Comment by straussmarkus** [comment]
Creating a new node sadly does not work either because of not being able to select a control

**Comment by codmpm** [comment]
Could you check the permission of the "new" user in the miniserver?

**Comment by straussmarkus** [comment]
It is an Administrator user already...

**Comment by codmpm** [comment]
Sadly we can not reproduce to counter check it. 
Did you already check node-red-log?

**Comment by straussmarkus** [comment]
Really not much either...

**Comment by straussmarkus** [comment]
Really not much either...

![Screenshot_20240506_153924_Termius](https://github.com/codmpm/node-red-contrib-loxone/assets/116552533/64b4d881-8a8a-4be0-a4cf-9e6860b3f17c)

**Comment by straussmarkus** [comment]
Today I updated my Miniserver to v15 and it started working again :)
