### ISSUE TITLE
Changing multiple lights in a Lighting Controller ends in only changing the first one

### ISSUE THREAD

**Issue by Programie** [codmpm/node-red-contrib-loxone#84]
I've a Lighting Controller with 3 outputs. I want to set the state of all 3 outputs using a function node.

For that, my function node has 3 outputs. Each of them is connected to a control-out node with the output of the Lighting Controller selected as "Control".

For some reason, whenever I send the 3 different payloads to the control-out nodes, only the first output is changed. But if I send the payload to only a single control-out node, the light state changes as expected. The same also works if I delay each message using the delay node.

My function node (with three outputs configured) looks like the following:

```javascript
return [
    { payload: 30 },
    { payload: 50 },
    { payload: true }
];
```

Then the function outputs are connected to three different control-out nodes with the respective outputs of the Lighting Controller being selected as "Control".

![image](https://github.com/codmpm/node-red-contrib-loxone/assets/1206521/f6796fb0-4703-4fc6-bc56-0987915c031c)

The flow looks like the following:

![image](https://github.com/codmpm/node-red-contrib-loxone/assets/1206521/6a9581db-2569-4a36-ae04-9254854c1f0b)

I'm not sure whether the issue only appears when using the outputs of the Lighting Controller. I never had any issues with controlling multiple outputs at the same time using other controllers or simple switches.

**Comment by ToRa89** [comment]
I had the same issues and my finding was, that the Miniserver cannot handle more than two inputs at the same time (Miniserver Gen. 1) and ignores the others. I then tried to control in your example the lights with master brightness. If there are different light controllers that have to be controlled, you can use a central light controller (don’t know the exact english term in lox config) or to use delays for middle lights and right lights nodes in node-red. So 200 ms delay for middle and 350 ms delay for right, no delay for table lights.
You can try it out, maybe lower delays are also possible.

**Comment by Programie** [comment]
Since I occurred the issue back in May, I added a delay as a workaround and it is working fine. But it would be much better if I wouldn't need that workaround.

So, I guess it's not a bug in the Loxone node and I will close the issue.
